apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adaptrain-controller-rolebinding
  namespace: adaptrain
subjects:
  - kind: ServiceAccount
    name: adaptrain-controller-sa
    namespace: adaptrain
roleRef:
  kind: Role
  name: adaptrain-controller-role
  apiGroup: rbac.authorization.k8s.io