apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: adaptrain
  name: adaptrain-controller-role
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "services"]
    verbs: ["create", "get", "list", "update", "delete"]